### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by dtracers** [jden/chai-interface#3]
This says on chai website this supports the browser but it actually does not.

Is there any plans for browser support in the future?

**Comment by junosuarez** [comment]
This package is not under active development, but I'm happy to review PRs and bug reports. It is implemented as plain old ES5 JavaScript, so there is no particular reason I know of that would prevent it from working in a browser. If there is a particular problem you are having, please provide some information like an error or stack trace, along with the browser and os you're using as well as the test runner.

Cheers!
